name: experiments
description: A modular scheduling library
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  data_class_plugin: any

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  tachyon: any
